export const GET_INFO_REQUEST = 'GET_INFO_REQUEST';
export const ADD_CARD_TO_LIST = 'ADD_CARD_TO_LIST';
export const GET_INFO_FAIL = 'GET_INFO_FAIL';

export const SET_INPUT_VALUE = 'SET_INPUT_VALUE';

export const REFRESH_CARD_REQUEST = 'REFRESH_CARD_REQUEST';
export const REFRESH_CARD_SUCCESS = 'REFRESH_CARD_SUCCESS';
export const REFRESH_CARD_FAIL = 'REFRESH_CARD_FAIL';

export const REMOVE_CARD_REQUEST = 'REMOVE_CARD_REQUEST';
export const REMOVE_CARD_SUCCESS = 'REMOVE_CARD_SUCCESS';
export const REMOVE_CARD_FAIL = 'REMOVE_CARD_FAIL';

export const ERROR_ACT = 'ERROR_ACT';


